### ISSUE TITLE
mobile app

### ISSUE THREAD

**Issue by fernandoveragul** [fernandoveragul/ar-project#5]
Сделать МВП со всеми диалоговыми окнами. Механизм работы с сетью для кнопки авторизации я сделаю, когда скажешь

**Comment by kazzrom** [comment]
1. Сделать все экраны приложения по макету, сделать возможность перехода между экранами.
2. Всё, что я понял и хотел, получилось. Экраны созданы, возможность перехода между ними есть.
3. -
4. -
