### ISSUE TITLE
qr

### ISSUE THREAD

**Issue by fernandoveragul** [fernandoveragul/ar-project#6]
Сделать рамочку вокруг кода, когда наводишься камерой. И тут же сделать небольшой интерфейс (функцию) чтобы она каждый кадр уже с рамочкой отдавала наружу. Пока что просто в оперативную память. Со следующим спринтом это нужно будет соединить с Ромой))
Я потом скажу как. Пока что просто рамочку

**Comment by MamBaf2** [comment]
1. Сделать рамочку при наведении камерой.
2.Сделали рамочку при наведении камеры на изображение с qr кодом(строки с обнаружением и вывода данных qr кода  заменили библиотекой pyzbar, вместо open cv), открытие камеры происходит через open cv. Максимально тупо сделали прерывание цикла при обнаружении qr кода, для того чтобы данные выводились 1 раз.
3. Изначально, при наведении камеры на qr код выводилась рамочка и данные считывались бесконечное кол-во раз, после добавления прерывания цикла, **рамочка не успевает нарисоваться**.
4. добавить интервал между обнаружением qr кода и прерыванием цикла, в след спринте исправим.
